= Toy Lisp devlog
:glsp: https://gamelisp.rs/[GameLisp]
:snowrl: https://github.com/toyboot4e/snowrl[SnowrL]
:cr: https://craftinginterpreters.com/contents.html[Crafting Interpreters]
:toy-scheme: https://github.com/toyboot4e/toy-scheme[toy-scheme]

== Background

I wanted to add scripting support for my game ({snowrl}) and {glsp} looked nice, but it didn't have `:named arg` syntax. Then I suddenly wanted to make my own Lisp: Toy Lisp (`tlp`).

I did {cr} (part II: tree-walk interpreter) in years ago. I made an Emacs package in ELisp ({toy-scheme}), but I know little about Lisp, so I'll have to struggle a lot.

== Devlog

=== Bytecode virtual machine

* Jun 9, 2021
+
I added a WIP lexer (tokenizer) which converts given string (`&str`) into a vector of tokens.
+
** The lexer handles non-streaming input/output or simplicity.
** The lexer handles UTF-8 string as bytes (as `&[u8]`, not as `&[char]`) because we're only interested in ASCII characters while lexing.

* Jun 12, 2021
+
Nice resource from `rustc` dev guide: https://rustc-dev-guide.rust-lang.org/the-parser.html[Lexing and Parsing]

* Jun 17, 2021
+
I parsed `Vec<Token>` into a hierarchy of tokens (S-expressions represented as spans of tokens in the vector). I'm not sure if it's a good idea to stick with tokens, but it doesn't lose any span of source code, so I'm going with it (for now).
=== TODOs

* Integration in my game?
* `serde`?

