[package]
name = "tlp"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.8.4"
log = "0.4.14"
thiserror = "1.0.25"

camino = "1.0.4"
rowan = "0.12.6"
salsa = "0.16.1"

paste = "1.0.5"
