[package]
name = "tlp"
version = "0.1.0"
edition = "2018"

[dependencies]
# std++
env_logger = "0.9.0"
log = "0.4.16"
thiserror = "1.0.30"
camino = "1.0.7"

# framework
rowan = "0.15.4"
salsa = "0.16.1"

# data structures and algorithms
rustc-hash = "1.1.0"
indexmap = "1.8.0"

# meta programming
paste = "1.0.6"
derivative = "2.2.0"

# optimization
smol_str = "0.1.21"
la-arena = "0.2.1"
nonmax = "0.5.0"

# utilities
itertools = "0.10.3"
